name: Build and Push API for base expenses

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      CONTAINER_REGISTRY: expensesapp
      IMAGE_NAME_EXPENSES: expenses-api
      IMAGE_NAME_MONITORING: expenses-monitoring

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker images
        run: |
          docker build -t ${{ env.IMAGE_NAME_EXPENSES }} --platform linux/amd64 -f Dockerfile .
          docker build -t ${{ env.IMAGE_NAME_MONITORING }} --platform linux/amd64 -f monitoring/Dockerfile .

      - name: Log in to Azure
        run: |
          az login 
          az account set --subscription azure_sponsorhip

      - name: Tag Docker images
        run: |
          docker tag ${{ env.IMAGE_NAME_EXPENSES }} ${{ env.CONTAINER_REGISTRY }}.azurecr.io/${{ env.IMAGE_NAME_EXPENSES }}:latest
          docker tag ${{ env.IMAGE_NAME_MONITORING }} ${{ env.CONTAINER_REGISTRY }}.azurecr.io/${{ env.IMAGE_NAME_MONITORING }}:latest

      - name: Log in to ACR
        run: |
          az acr login --name ${{ env.CONTAINER_REGISTRY }}

      - name: Push Docker images
        run: |
          docker push ${{ env.CONTAINER_REGISTRY }}.azurecr.io/${{ env.IMAGE_NAME_EXPENSES }}:latest
          docker push ${{ env.CONTAINER_REGISTRY }}.azurecr.io/${{ env.IMAGE_NAME_MONITORING }}:latest